title: Test Site
icon: /assets/img/icon.png
permalink: /:categories/:year/:month/:day/:title
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      category: news
  - scope:
      path: ""
    values:
      layout: default
plugins:
 - jekyll-menus